"""Run the G-code validator against known-good and unsafe fixtures."""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from validate_gcode import validate  # noqa: E402
from ensure_m99123_first import convert_m204_line, insert_next_tool_preheat, rewrite  # noqa: E402

FIXTURES = ROOT / "tests" / "fixtures"


class GcodeSafetyTests(unittest.TestCase):
    def test_ideamaker_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "ideamaker_left_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))

    def test_unsafe_fixture_fails(self) -> None:
        errors = validate(FIXTURES / "unsafe_commands.gcode")
        joined = "\n".join(errors)
        self.assertTrue(any("G29" in e for e in errors), joined)
        self.assertTrue(any("M92" in e for e in errors), joined)
        self.assertTrue(any("M600" in e for e in errors), joined)

    def test_dual_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "dual_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))

    def test_ideamaker_dual_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "ideamaker_dual_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))

    def test_start_only_is_not_a_complete_job(self) -> None:
        errors = validate(FIXTURES / "ideamaker_left_start.gcode")
        self.assertTrue(any("M1002" in e for e in errors))
        self.assertTrue(any("shutdown" in e.lower() or "M104 S0" in e or "M84" in e for e in errors))

    def test_ensure_m99123_first_moves_prusaslicer_preamble(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        self.assertTrue(src.startswith("M99123 "))
        preamble = (
            "; generated by PrusaSlicer 2.9.6 on 2026-08-25 at 16:06:58 UTC\n"
            "\n"
            "; thumbnail begin 32x32 12\n"
            "; AAAA\n"
            "; thumbnail end\n"
            "\n"
            ";TYPE:Custom\n"
        )
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "slice.gcode"
            path.write_text(preamble + src, encoding="utf-8", newline="\n")
            errors_before = validate(path)
            self.assertTrue(any("M99123" in e and "line 1" in e for e in errors_before))
            self.assertEqual(rewrite(path), "moved")
            out = path.read_text(encoding="utf-8")
            self.assertTrue(out.startswith("M99123 "))
            self.assertIn("; generated by PrusaSlicer", out)
            self.assertEqual(rewrite(path), "already")
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))

    def test_ensure_m99123_first_missing_header(self) -> None:
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "nohs.gcode"
            path.write_text("G28 X0 Y0\n", encoding="utf-8")
            self.assertEqual(rewrite(path), "missing")

    def test_convert_m204_matches_ideamaker_set_velocity_limit(self) -> None:
        self.assertEqual(convert_m204_line("M204 S2000"), "SET_VELOCITY_LIMIT ACCEL=2000.00")
        self.assertEqual(convert_m204_line("M204 S5000"), "SET_VELOCITY_LIMIT ACCEL=5000.00")
        self.assertEqual(
            convert_m204_line("M204 S2500 ; adjust acceleration"),
            "SET_VELOCITY_LIMIT ACCEL=2500.00; adjust acceleration",
        )
        self.assertEqual(convert_m204_line("G1 X10"), "G1 X10")

    def test_rewrite_converts_m204(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "m204.gcode"
            path.write_text(src.replace("G1 X110 E5", "M204 S2000\nG1 X110 E5", 1), encoding="utf-8")
            self.assertTrue(any("M204" in e for e in validate(path)))
            self.assertEqual(rewrite(path), "already")
            out = path.read_text(encoding="utf-8")
            self.assertIn("SET_VELOCITY_LIMIT ACCEL=2000.00", out)
            self.assertNotIn("M204", out)
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))

    def test_next_tool_preheat_inserts_m104_before_swap_wait(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        out, n = insert_next_tool_preheat(src)
        self.assertEqual(n, 0)
        self.assertEqual(out, src)

        g1_idx = next(i for i, line in enumerate(src) if line.startswith("G1 X100"))
        padded = src[: g1_idx + 1] + ["G1 X101 E0.1"] * 500 + src[g1_idx + 1 :]
        out, n = insert_next_tool_preheat(padded)
        self.assertEqual(n, 1)
        pre = [line for line in out if "next-tool preheat" in line]
        self.assertEqual(len(pre), 1)
        self.assertIn("M104 T1 S205", pre[0])
        m1001 = next(i for i, line in enumerate(out) if line.strip() == "M1001")
        pre_i = next(i for i, line in enumerate(out) if "next-tool preheat" in line)
        wait_i = next(
            i for i, line in enumerate(out) if i > m1001 and line.startswith("M109 T1")
        )
        self.assertLess(pre_i, wait_i)
        self.assertGreater(pre_i, m1001)
        out2, n2 = insert_next_tool_preheat(out)
        self.assertEqual(n2, 0)

    def test_t1_left_keepout_after_m1001_fails(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        poisoned = src.replace("G1 X120 Y100 E8", "G1 X10 Y100 E8", 1)
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "t1_keepout.gcode"
            path.write_text(poisoned, encoding="utf-8")
            errors = validate(path)
        joined = "\n".join(errors)
        self.assertTrue(any("T1" in e and "keep-out" in e for e in errors), joined)

    def test_t0_left_of_keepout_after_m1001_is_ok(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        t0_left = src.replace("G1 X100 Y100 Z0.3 F900", "G1 X10 Y100 Z0.3 F900", 1)
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "t0_left.gcode"
            path.write_text(t0_left, encoding="utf-8")
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))


if __name__ == "__main__":
    unittest.main()
