"""Run the G-code validator against known-good and unsafe fixtures."""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from validate_gcode import validate  # noqa: E402
from ensure_m99123_first import (  # noqa: E402
    convert_m204_line,
    emit_raisetouch_times,
    insert_next_tool_preheat,
    parse_hms,
    rewrite,
)

FIXTURES = ROOT / "tests" / "fixtures"


class GcodeSafetyTests(unittest.TestCase):
    def test_ideamaker_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "ideamaker_left_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))

    def test_unsafe_fixture_fails(self) -> None:
        errors = validate(FIXTURES / "unsafe_commands.gcode")
        joined = "\n".join(errors)
        self.assertTrue(any("G29" in e for e in errors), joined)
        self.assertTrue(any("M92" in e for e in errors), joined)
        self.assertTrue(any("M600" in e for e in errors), joined)

    def test_dual_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "dual_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))

    def test_ideamaker_right_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "ideamaker_right_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))

    def test_ideamaker_dual_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "ideamaker_dual_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))


    def test_start_only_is_not_a_complete_job(self) -> None:
        errors = validate(FIXTURES / "ideamaker_left_start.gcode")
        self.assertTrue(any("M1002" in e for e in errors))
        self.assertTrue(any("shutdown" in e.lower() or "M104 S0" in e or "M84" in e for e in errors))

    def test_ensure_m99123_first_moves_prusaslicer_preamble(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        self.assertTrue(src.startswith("M99123 "))
        preamble = (
            "; generated by PrusaSlicer 2.9.6 on 2026-08-25 at 16:06:58 UTC\n"
            "\n"
            "; thumbnail begin 32x32 12\n"
            "; AAAA\n"
            "; thumbnail end\n"
            "\n"
            ";TYPE:Custom\n"
        )
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "slice.gcode"
            path.write_text(preamble + src, encoding="utf-8", newline="\n")
            errors_before = validate(path)
            self.assertTrue(any("M99123" in e and "line 1" in e for e in errors_before))
            self.assertEqual(rewrite(path), "moved")
            out = path.read_text(encoding="utf-8")
            self.assertTrue(out.startswith("M99123 "))
            self.assertIn("; generated by PrusaSlicer", out)
            self.assertEqual(rewrite(path), "already")
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))

    def test_ensure_m99123_first_missing_header(self) -> None:
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "nohs.gcode"
            path.write_text("G28 X0 Y0\n", encoding="utf-8")
            self.assertEqual(rewrite(path), "missing")

    def test_convert_m204_matches_ideamaker_set_velocity_limit(self) -> None:
        self.assertEqual(convert_m204_line("M204 S2000"), "SET_VELOCITY_LIMIT ACCEL=2000.00")
        self.assertEqual(convert_m204_line("M204 S5000"), "SET_VELOCITY_LIMIT ACCEL=5000.00")
        self.assertEqual(
            convert_m204_line("M204 S2500 ; adjust acceleration"),
            "SET_VELOCITY_LIMIT ACCEL=2500.00; adjust acceleration",
        )
        self.assertEqual(convert_m204_line("G1 X10"), "G1 X10")

    def test_rewrite_converts_m204(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "m204.gcode"
            path.write_text(src.replace("G1 X110 E5", "M204 S2000\nG1 X110 E5", 1), encoding="utf-8")
            self.assertTrue(any("M204" in e for e in validate(path)))
            self.assertEqual(rewrite(path), "already")
            out = path.read_text(encoding="utf-8")
            self.assertIn("SET_VELOCITY_LIMIT ACCEL=2000.00", out)
            self.assertNotIn("M204", out)
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))

    def test_next_tool_preheat_inserts_m104_before_swap_wait(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        out, n = insert_next_tool_preheat(src)
        self.assertEqual(n, 0)
        self.assertEqual(out, src)

        g1_idx = next(i for i, line in enumerate(src) if line.startswith("G1 X100"))
        padded = src[: g1_idx + 1] + ["G1 X101 E0.1"] * 500 + src[g1_idx + 1 :]
        out, n = insert_next_tool_preheat(padded)
        self.assertEqual(n, 1)
        pre = [line for line in out if "next-tool preheat" in line]
        self.assertEqual(len(pre), 1)
        self.assertIn("M104 T1 S205", pre[0])
        m1001 = next(i for i, line in enumerate(out) if line.strip() == "M1001")
        pre_i = next(i for i, line in enumerate(out) if "next-tool preheat" in line)
        wait_i = next(
            i for i, line in enumerate(out) if i > m1001 and line.startswith("M109 T1")
        )
        self.assertLess(pre_i, wait_i)
        self.assertGreater(pre_i, m1001)
        out2, n2 = insert_next_tool_preheat(out)
        self.assertEqual(n2, 0)

    def test_t1_left_keepout_after_m1001_fails(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        poisoned = src.replace("G1 X120 Y100 E8", "G1 X10 Y100 E8", 1)
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "t1_keepout.gcode"
            path.write_text(poisoned, encoding="utf-8")
            errors = validate(path)
        joined = "\n".join(errors)
        self.assertTrue(any("T1" in e and "keep-out" in e for e in errors), joined)

    def test_t0_left_of_keepout_after_m1001_is_ok(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        t0_left = src.replace("G1 X100 Y100 Z0.3 F900", "G1 X10 Y100 Z0.3 F900", 1)
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "t0_left.gcode"
            path.write_text(t0_left, encoding="utf-8")
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))

    def test_parse_hms(self) -> None:
        self.assertEqual(parse_hms("3h 16m 9s"), 3 * 3600 + 16 * 60 + 9)
        self.assertEqual(parse_hms("45m 12s"), 45 * 60 + 12)
        self.assertEqual(parse_hms("30s"), 30)

    def test_emit_raisetouch_times_from_m73_and_stats(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        g1 = next(i for i, line in enumerate(src) if line.startswith("G1 X100"))
        padded = (
            src[: g1 + 1]
            + ["M73 P0 R193", "M73 P50 R96"]
            + src[g1 + 1 :]
            + [
                "; filament used [mm] = 20436.15, 0.00",
                "; filament cost = 1.22, 0.00",
                "; estimated printing time (normal mode) = 3h 13m 0s",
            ]
        )
        out, n = emit_raisetouch_times(padded)
        self.assertGreaterEqual(n, 3)
        self.assertNotIn("M73 P0 R193", out)
        self.assertIn(";PRINTING_TIME: 0", out)
        self.assertIn(";REMAINING_TIME: 11580", out)
        self.assertIn(";PRINTING_TIME: 5820", out)
        self.assertIn(";REMAINING_TIME: 5760", out)
        self.assertIn(";Print Time: 11580", out)
        self.assertIn(";Material#1 Used: 20436.2", out)
        self.assertIn(";Material#1 Cost: 1.22", out)
        out2, n2 = emit_raisetouch_times(out)
        self.assertEqual(n2, 0)

    def test_rewrite_is_idempotent_after_raisetouch_times(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "times.gcode"
            path.write_text(
                src
                + "\n; estimated printing time (normal mode) = 1h 0m 0s\n"
                + "M73 P0 R60\n",
                encoding="utf-8",
            )
            self.assertEqual(rewrite(path), "already")
            first = path.read_text(encoding="utf-8")
            self.assertIn(";REMAINING_TIME: 3600", first)
            self.assertNotIn("M73 P0 R60", first)
            self.assertEqual(rewrite(path), "already")
            self.assertEqual(path.read_text(encoding="utf-8"), first)
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))


if __name__ == "__main__":
    unittest.main()
