"""Post-process PrusaSlicer G-code for this Raise3D Hyper Speed printer.

1. Move M99123 to physical line 1 (PrusaSlicer always prepends `; generated by …`).
2. Rewrite PrusaSlicer's Klipper-flavor `M204 S…` as ideaMaker `SET_VELOCITY_LIMIT ACCEL=…`.
3. Insert mid-print `M104 T{next}` before each swap `M109` (ideaMaker preheats while the
   other nozzle is still printing). `next_extruder` exists only in tool-change G-code.

Works as a CLI (`python scripts/ensure_m99123_first.py file.gcode`) and as a
PrusaSlicer post-processing script (G-code path is the last argument).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

M204_S = re.compile(r"^M204\b(?P<body>.*)$", re.I)
M204_S_VAL = re.compile(r"\bS(-?\d+(?:\.\d+)?)", re.I)
M109_T = re.compile(r"^M109\s+T([01])\s+S(\d+(?:\.\d+)?)\b", re.I)
M104_T = re.compile(r"^M104\s+T([01])\s+S(-?\d+(?:\.\d+)?)\b", re.I)
T_SEL = re.compile(r"^T([01])\b", re.I)
# ideaMaker Multicolor median gap preheat→M109 is ~285 lines (range ~200–2600).
PREHEAT_LINES = 400
MIN_PREHEAT_GAP = 50


def _code(line: str) -> str:
    return line.split(";", 1)[0].strip()


def insert_next_tool_preheat(lines: list[str]) -> tuple[list[str], int]:
    """Insert M104 Tn S… while the other tool is still printing, before each swap M109.

    PrusaSlicer 2.9.6 has next_extruder only in toolchange G-code (too late).
    ideaMaker Multicolor emits M104 T{next} S230 mid-print, then M109 at the swap.
    """
    try:
        m1001 = next(i for i, line in enumerate(lines) if _code(line).upper() == "M1001")
        m1002 = next(i for i, line in enumerate(lines) if _code(line).upper() == "M1002")
    except StopIteration:
        return lines, 0

    waits: list[tuple[int, int, str]] = []
    for i in range(m1001 + 1, m1002):
        match = M109_T.match(_code(lines[i]))
        if not match:
            continue
        temp = float(match.group(2))
        if temp < 50:
            continue
        waits.append((i, int(match.group(1)), match.group(2)))

    to_insert: list[tuple[int, str]] = []
    for wait_i, tool, temp_s in waits:
        last_t_idx = None
        last_t = None
        for j in range(wait_i - 1, -1, -1):
            match = T_SEL.match(_code(lines[j]))
            if match:
                last_t_idx = j
                last_t = int(match.group(1))
                break
        if last_t is None or last_t == tool:
            continue

        stint_start = max(m1001 + 1, last_t_idx + 1)
        if wait_i - stint_start < MIN_PREHEAT_GAP:
            continue

        already = False
        for j in range(stint_start, wait_i):
            match = M104_T.match(_code(lines[j]))
            if match and int(match.group(1)) == tool and abs(float(match.group(2)) - float(temp_s)) < 1:
                already = True
                break
        if already:
            continue

        insert_at = max(stint_start, wait_i - PREHEAT_LINES)
        if wait_i - insert_at < MIN_PREHEAT_GAP:
            continue
        to_insert.append(
            (insert_at, f"M104 T{tool} S{temp_s} ; next-tool preheat (ideaMaker Multicolor)")
        )

    out = list(lines)
    for insert_at, text in sorted(to_insert, key=lambda item: item[0], reverse=True):
        out.insert(insert_at, text)
    return out, len(to_insert)


def convert_m204_line(line: str) -> str:
    """Turn `M204 S2000` into `SET_VELOCITY_LIMIT ACCEL=2000.00`. Leave other lines."""
    code, sep, comment = line.partition(";")
    stripped = code.strip()
    if not M204_S.match(stripped):
        return line
    match = M204_S_VAL.search(stripped)
    if match is None:
        return line
    accel = float(match.group(1))
    out = f"SET_VELOCITY_LIMIT ACCEL={accel:.2f}"
    if sep:
        out += f";{comment}"
    return out


def convert_m204_lines(lines: list[str]) -> tuple[list[str], int]:
    out = []
    n = 0
    for line in lines:
        converted = convert_m204_line(line)
        if converted != line:
            n += 1
        out.append(converted)
    return out, n


def rewrite(path: Path) -> str:
    """Move M99123 to line 1, convert M204, insert next-tool preheat.

    Returns 'moved', 'already', or 'missing' (M99123 status).
    """
    raw = path.read_bytes()
    newline = b"\r\n" if b"\r\n" in raw else b"\n"
    text = raw.decode("utf-8-sig", errors="replace")
    lines = text.splitlines()
    lines, n_m204 = convert_m204_lines(lines)
    lines, n_preheat = insert_next_tool_preheat(lines)
    idx = next((i for i, line in enumerate(lines) if line.startswith("M99123")), None)
    moved = False
    if idx is not None and idx != 0:
        header = lines.pop(idx)
        lines.insert(0, header)
        moved = True
    if moved or n_m204 or n_preheat:
        path.write_bytes((newline.decode("ascii").join(lines) + newline.decode("ascii")).encode("utf-8"))
    if idx is None:
        return "missing"
    return "moved" if moved else "already"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "gcode",
        nargs="?",
        type=Path,
        help="G-code path (PrusaSlicer post-process passes this as the last arg)",
    )
    args, extra = parser.parse_known_args(argv)
    path = args.gcode
    if extra:
        # Post-process: slicer may pass flags then the temp file as the last token.
        path = Path(extra[-1])
    if path is None:
        parser.error("gcode path required")
    if not path.is_file():
        print(f"not found: {path}", file=sys.stderr)
        return 1
    raw_before = path.read_text(encoding="utf-8", errors="replace")
    m204_before = sum(1 for line in raw_before.splitlines() if M204_S.match(line.split(";", 1)[0].strip()))
    result = rewrite(path)
    extra_msg = f", converted {m204_before} M204 to SET_VELOCITY_LIMIT" if m204_before else ""
    if "next-tool preheat" in path.read_text(encoding="utf-8", errors="replace"):
        extra_msg += ", inserted next-tool M104 preheat"
    if result == "missing":
        print(f"FAIL {path}: no M99123 line to move{extra_msg}", file=sys.stderr)
        return 1
    if result == "already":
        print(f"OK {path}: M99123 already on line 1{extra_msg}")
    else:
        print(f"OK {path}: moved M99123 to line 1{extra_msg}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
