"""Move the Hyper Speed M99123 line to line 1 of a PrusaSlicer G-code file.

PrusaSlicer always prepends `; generated by …` and, if enabled, PNG thumbnails.
ideaMaker Hyper Speed files start with M99123; RaiseTouch is reported to look
at that first line. This script rewrites the file in place.

Works as a CLI (`python scripts/ensure_m99123_first.py file.gcode`) and as a
PrusaSlicer post-processing script (G-code path is the last argument).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def rewrite(path: Path) -> str:
    """Move the first M99123 line to the top. Returns 'moved', 'already', or 'missing'."""
    raw = path.read_bytes()
    newline = b"\r\n" if b"\r\n" in raw else b"\n"
    text = raw.decode("utf-8-sig", errors="replace")
    lines = text.splitlines()
    idx = next((i for i, line in enumerate(lines) if line.startswith("M99123")), None)
    if idx is None:
        return "missing"
    if idx == 0:
        return "already"
    header = lines.pop(idx)
    lines.insert(0, header)
    path.write_bytes((newline.decode("ascii").join(lines) + newline.decode("ascii")).encode("utf-8"))
    return "moved"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "gcode",
        nargs="?",
        type=Path,
        help="G-code path (PrusaSlicer post-process passes this as the last arg)",
    )
    args, extra = parser.parse_known_args(argv)
    path = args.gcode
    if extra:
        # Post-process: slicer may pass flags then the temp file as the last token.
        path = Path(extra[-1])
    if path is None:
        parser.error("gcode path required")
    if not path.is_file():
        print(f"not found: {path}", file=sys.stderr)
        return 1
    result = rewrite(path)
    if result == "missing":
        print(f"FAIL {path}: no M99123 line to move", file=sys.stderr)
        return 1
    if result == "already":
        print(f"OK {path}: M99123 already on line 1")
    else:
        print(f"OK {path}: moved M99123 to line 1")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
