"""Post-process PrusaSlicer G-code for this Raise3D Hyper Speed printer.

1. Move M99123 to physical line 1 (PrusaSlicer always prepends `; generated by …`).
2. Rewrite PrusaSlicer's Klipper-flavor `M204 S…` as ideaMaker `SET_VELOCITY_LIMIT ACCEL=…`.
   Stock PrusaSlicer 2.9.6 never emits SET_VELOCITY_LIMIT for per-feature accel
   (GCodeWriter uses M204 S). Klipper accepts both; this machine's ideaMaker files
   use SET_VELOCITY_LIMIT ACCEL=2000/5000.

Works as a CLI (`python scripts/ensure_m99123_first.py file.gcode`) and as a
PrusaSlicer post-processing script (G-code path is the last argument).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

M204_S = re.compile(r"^M204\b(?P<body>.*)$", re.I)
M204_S_VAL = re.compile(r"\bS(-?\d+(?:\.\d+)?)", re.I)


def convert_m204_line(line: str) -> str:
    """Turn `M204 S2000` into `SET_VELOCITY_LIMIT ACCEL=2000.00`. Leave other lines."""
    code, sep, comment = line.partition(";")
    stripped = code.strip()
    if not M204_S.match(stripped):
        return line
    match = M204_S_VAL.search(stripped)
    if match is None:
        return line
    accel = float(match.group(1))
    out = f"SET_VELOCITY_LIMIT ACCEL={accel:.2f}"
    if sep:
        out += f";{comment}"
    return out


def convert_m204_lines(lines: list[str]) -> tuple[list[str], int]:
    out = []
    n = 0
    for line in lines:
        converted = convert_m204_line(line)
        if converted != line:
            n += 1
        out.append(converted)
    return out, n


def rewrite(path: Path) -> str:
    """Move M99123 to line 1 and convert M204. Returns 'moved', 'already', or 'missing'."""
    raw = path.read_bytes()
    newline = b"\r\n" if b"\r\n" in raw else b"\n"
    text = raw.decode("utf-8-sig", errors="replace")
    lines = text.splitlines()
    lines, n_m204 = convert_m204_lines(lines)
    idx = next((i for i, line in enumerate(lines) if line.startswith("M99123")), None)
    moved = False
    if idx is not None and idx != 0:
        header = lines.pop(idx)
        lines.insert(0, header)
        moved = True
    if moved or n_m204:
        path.write_bytes((newline.decode("ascii").join(lines) + newline.decode("ascii")).encode("utf-8"))
    if idx is None:
        return "missing"
    return "moved" if moved else "already"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "gcode",
        nargs="?",
        type=Path,
        help="G-code path (PrusaSlicer post-process passes this as the last arg)",
    )
    args, extra = parser.parse_known_args(argv)
    path = args.gcode
    if extra:
        # Post-process: slicer may pass flags then the temp file as the last token.
        path = Path(extra[-1])
    if path is None:
        parser.error("gcode path required")
    if not path.is_file():
        print(f"not found: {path}", file=sys.stderr)
        return 1
    raw_before = path.read_text(encoding="utf-8", errors="replace")
    m204_before = sum(1 for line in raw_before.splitlines() if M204_S.match(line.split(";", 1)[0].strip()))
    result = rewrite(path)
    extra_msg = f", converted {m204_before} M204 to SET_VELOCITY_LIMIT" if m204_before else ""
    if result == "missing":
        print(f"FAIL {path}: no M99123 line to move{extra_msg}", file=sys.stderr)
        return 1
    if result == "already":
        print(f"OK {path}: M99123 already on line 1{extra_msg}")
    else:
        print(f"OK {path}: moved M99123 to line 1{extra_msg}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
