"""Post-process PrusaSlicer G-code for this Raise3D Hyper Speed printer.

1. Move M99123 to physical line 1 (PrusaSlicer always prepends `; generated by …`).
2. Rewrite PrusaSlicer's Klipper-flavor `M204 S…` as ideaMaker `SET_VELOCITY_LIMIT ACCEL=…`.
3. Insert mid-print `M104 T{next}` before each swap `M109` (ideaMaker preheats while the
   other nozzle is still printing). `next_extruder` exists only in tool-change G-code.
4. Convert PrusaSlicer `M73 P… R…` (percent / minutes) to ideaMaker
   `;PRINTING_TIME:` / `;REMAINING_TIME:` (seconds), synthesize `;LAYER:0` after
   `M1001` when PrusaSlicer omitted it, and append `;Print Time:` /
   `;Material#N Used:` so RaiseTouch can show progress, remaining time, and file stats.

Works as a CLI (`python scripts/ensure_m99123_first.py file.gcode`) and as a
PrusaSlicer post-processing script (G-code path is the last argument).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

M204_S = re.compile(r"^M204\b(?P<body>.*)$", re.I)
M204_S_VAL = re.compile(r"\bS(-?\d+(?:\.\d+)?)", re.I)
M109_T = re.compile(r"^M109\s+T([01])\s+S(\d+(?:\.\d+)?)\b", re.I)
M104_T = re.compile(r"^M104\s+T([01])\s+S(-?\d+(?:\.\d+)?)\b", re.I)
T_SEL = re.compile(r"^T([01])\b", re.I)
M73 = re.compile(r"^M73\b(?P<body>.*)$", re.I)
LAYER_NUM = re.compile(r"^;LAYER:(\d+)\s*$")
HEIGHT_LINE = re.compile(r"^;HEIGHT:(-?\d+(?:\.\d+)?)\s*$")
Z_LINE = re.compile(r"^;Z:(-?\d+(?:\.\d+)?)\s*$")
BBOX_LINE = re.compile(
    r"^;Bounding Box:\s+"
    r"(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s+"
    r"(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s+"
    r"(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s*$"
)
MOVE_CMD = re.compile(r"^G([0123])\b", re.I)
AXIS_XY = re.compile(r"\b([XY])(-?\d+(?:\.\d+)?)", re.I)
EST_TIME = re.compile(r"^;\s*estimated printing time \(normal mode\)\s*=\s*(.+)$", re.I)
FILAMENT_MM = re.compile(r"^;\s*filament used \[mm\]\s*=\s*(.+)$", re.I)
FILAMENT_COST = re.compile(r"^;\s*filament cost\s*=\s*(.+)$", re.I)
# ideaMaker Multicolor median gap preheat→M109 is ~285 lines (range ~200–2600).
PREHEAT_LINES = 400
MIN_PREHEAT_GAP = 50


def _code(line: str) -> str:
    return line.split(";", 1)[0].strip()


def insert_next_tool_preheat(lines: list[str]) -> tuple[list[str], int]:
    """Insert M104 Tn S… while the other tool is still printing, before each swap M109.

    PrusaSlicer 2.9.6 has next_extruder only in toolchange G-code (too late).
    ideaMaker Multicolor emits M104 T{next} S230 mid-print, then M109 at the swap.
    """
    try:
        m1001 = next(i for i, line in enumerate(lines) if _code(line).upper() == "M1001")
        m1002 = next(i for i, line in enumerate(lines) if _code(line).upper() == "M1002")
    except StopIteration:
        return lines, 0

    waits: list[tuple[int, int, str]] = []
    for i in range(m1001 + 1, m1002):
        match = M109_T.match(_code(lines[i]))
        if not match:
            continue
        temp = float(match.group(2))
        if temp < 50:
            continue
        waits.append((i, int(match.group(1)), match.group(2)))

    to_insert: list[tuple[int, str]] = []
    for wait_i, tool, temp_s in waits:
        last_t_idx = None
        last_t = None
        for j in range(wait_i - 1, -1, -1):
            match = T_SEL.match(_code(lines[j]))
            if match:
                last_t_idx = j
                last_t = int(match.group(1))
                break
        if last_t is None or last_t == tool:
            continue

        stint_start = max(m1001 + 1, last_t_idx + 1)
        if wait_i - stint_start < MIN_PREHEAT_GAP:
            continue

        already = False
        for j in range(stint_start, wait_i):
            match = M104_T.match(_code(lines[j]))
            if match and int(match.group(1)) == tool and abs(float(match.group(2)) - float(temp_s)) < 1:
                already = True
                break
        if already:
            continue

        insert_at = max(stint_start, wait_i - PREHEAT_LINES)
        if wait_i - insert_at < MIN_PREHEAT_GAP:
            continue
        to_insert.append(
            (insert_at, f"M104 T{tool} S{temp_s} ; next-tool preheat (ideaMaker Multicolor)")
        )

    out = list(lines)
    for insert_at, text in sorted(to_insert, key=lambda item: item[0], reverse=True):
        out.insert(insert_at, text)
    return out, len(to_insert)


def convert_m204_line(line: str) -> str:
    """Turn `M204 S2000` into `SET_VELOCITY_LIMIT ACCEL=2000.00`. Leave other lines."""
    code, sep, comment = line.partition(";")
    stripped = code.strip()
    if not M204_S.match(stripped):
        return line
    match = M204_S_VAL.search(stripped)
    if match is None:
        return line
    accel = float(match.group(1))
    out = f"SET_VELOCITY_LIMIT ACCEL={accel:.2f}"
    if sep:
        out += f";{comment}"
    return out


def convert_m204_lines(lines: list[str]) -> tuple[list[str], int]:
    out = []
    n = 0
    for line in lines:
        converted = convert_m204_line(line)
        if converted != line:
            n += 1
        out.append(converted)
    return out, n


def parse_hms(text: str) -> int:
    """Parse PrusaSlicer `3h 16m 9s` / `45m` / `30s` into seconds."""
    hours = minutes = seconds = 0
    if match := re.search(r"(\d+)\s*h", text, re.I):
        hours = int(match.group(1))
    if match := re.search(r"(\d+)\s*m", text, re.I):
        minutes = int(match.group(1))
    if match := re.search(r"(\d+)\s*s", text, re.I):
        seconds = int(match.group(1))
    return hours * 3600 + minutes * 60 + seconds


def _csv_floats(text: str) -> list[float]:
    out = []
    for part in text.split(","):
        part = part.strip()
        if not part:
            continue
        try:
            out.append(float(part))
        except ValueError:
            continue
    return out


def parse_estimated_seconds(lines: list[str]) -> int | None:
    for line in lines:
        match = EST_TIME.match(line.strip())
        if match:
            return parse_hms(match.group(1))
    return None


def parse_filament_stats(lines: list[str]) -> tuple[list[float], list[float]]:
    mm: list[float] = []
    cost: list[float] = []
    for line in lines:
        stripped = line.strip()
        match = FILAMENT_MM.match(stripped)
        if match:
            mm = _csv_floats(match.group(1))
            continue
        match = FILAMENT_COST.match(stripped)
        if match:
            cost = _csv_floats(match.group(1))
    return mm, cost


def _layer_num(line: str) -> int | None:
    match = LAYER_NUM.match(line.strip())
    return int(match.group(1)) if match else None


def _layer_marker(line: str, prefer_layer_change: bool) -> bool:
    """ideaMaker / RaiseTouch key off `;LAYER:N`, not PrusaSlicer's `;LAYER_CHANGE`."""
    if prefer_layer_change:
        return line.strip().startswith(";LAYER_CHANGE")
    return _layer_num(line) is not None


def _strip_orphaned_layer_times(lines: list[str], keep_layer_change: bool) -> list[str]:
    """Drop time comments that are not immediately before the RaiseTouch layer marker."""
    out: list[str] = []
    i = 0
    while i < len(lines):
        if (
            i + 2 < len(lines)
            and lines[i].startswith(";PRINTING_TIME:")
            and lines[i + 1].startswith(";REMAINING_TIME:")
            and (
                _layer_num(lines[i + 2]) is not None
                or (keep_layer_change and lines[i + 2].strip().startswith(";LAYER_CHANGE"))
            )
        ):
            out.append(lines[i])
            out.append(lines[i + 1])
            i += 2
            continue
        if lines[i].startswith(";PRINTING_TIME:") or lines[i].startswith(";REMAINING_TIME:"):
            i += 1
            continue
        out.append(lines[i])
        i += 1
    return out


def _material_comments(total: int, mm: list[float], cost: list[float]) -> list[str]:
    out = [f";Print Time: {total}"]
    for i, used in enumerate(mm or [0.0], start=1):
        if used <= 0 and i > 1:
            continue
        out.append(f";Material#{i} Used: {used:.1f}")
        if i <= len(cost):
            out.append(f";Material#{i} Cost: {cost[i - 1]:.2f}")
    return out


def _clock_from_m73(
    total: int | None, remaining: int | None, pct: float | None
) -> tuple[int, int] | None:
    """Map Prusa M73 (P percent, R minutes) to ideaMaker second clocks.

    At P=0 use the footer second total so layer 0 is not off by M73's minute rounding.
    """
    if remaining is None and total is not None and pct is not None:
        remaining = int(round(total * (100.0 - min(max(pct, 0.0), 100.0)) / 100.0))
    if remaining is None:
        return None
    if total is None:
        total = remaining
    if pct is not None and pct <= 0:
        return 0, total
    if pct is not None and pct >= 100:
        return total, 0
    printed = min(max(total - remaining, 0), total)
    return printed, total - printed


def _first_layer_change_zh(lines: list[str]) -> tuple[str | None, str | None]:
    """First `;Z:` / `;HEIGHT:` after M1001 (PrusaSlicer `;LAYER_CHANGE` block)."""
    after_m1001 = False
    z_line = None
    h_line = None
    for line in lines:
        if _code(line).upper() == "M1001":
            after_m1001 = True
            continue
        if not after_m1001:
            continue
        stripped = line.strip()
        if z_line is None and Z_LINE.match(stripped):
            z_line = stripped
        if h_line is None and HEIGHT_LINE.match(stripped):
            h_line = stripped
        if z_line is not None and h_line is not None:
            break
    return z_line, h_line


def _ensure_layer0_after_m1001(lines: list[str], total: int) -> tuple[list[str], int]:
    """PrusaSlicer skips before_layer_gcode on the first layer — synthesize ideaMaker LAYER:0."""
    if any(_layer_num(line) == 0 for line in lines):
        return lines, 0
    try:
        m1001 = next(i for i, line in enumerate(lines) if _code(line).upper() == "M1001")
    except StopIteration:
        return lines, 0
    z_line, h_line = _first_layer_change_zh(lines)
    block = [";PRINTING_TIME: 0", f";REMAINING_TIME: {total}", ";LAYER:0"]
    if z_line:
        block.append(z_line)
    if h_line:
        block.append(h_line)
    return lines[: m1001 + 1] + block + lines[m1001 + 1 :], 1


def emit_raisetouch_times(lines: list[str]) -> tuple[list[str], int]:
    """Write ideaMaker time comments RaiseTouch reads at `;LAYER:N`.

    ideaMaker 4.1.0: `;PRINTING_TIME:` / `;REMAINING_TIME:` are seconds printed /
    seconds remaining. Known-good files put those two lines immediately before
    `;LAYER:N` (then `;Z:` / `;HEIGHT:`). PrusaSlicer remaining_times emits `M73`
    with `R` in minutes (Prusa firmware); RaiseTouch does not use `M73`.
    PrusaSlicer also writes `;LAYER_CHANGE`; attaching times there leaves `;Z:` /
    `;HEIGHT:` between the clock and `;LAYER:`, and RaiseTouch ignores them.
    Do not put `HEIGHT` in custom G-code (PrusaSlicer reserved keyword). Copy the
    slicer's own `;HEIGHT:` after `;LAYER:N` / `;Z:` in post-process instead.
    PrusaSlicer skips Before layer change G-code on the first layer, so there is
    no `;LAYER:0` to hang the clock on. Synthesize that ideaMaker block after
    `M1001` (times plus the first `;LAYER_CHANGE` `;Z:` / `;HEIGHT:`).
    File-picker grams/price/thumbnail still come from ideaMaker `.data`.
    """
    has_layer_num = any(_layer_num(line) is not None for line in lines)
    prefer_lc = not has_layer_num
    lines = _strip_orphaned_layer_times(lines, keep_layer_change=prefer_lc)

    total = parse_estimated_seconds(lines)
    mm, cost = parse_filament_stats(lines)
    layer_ns = [_layer_num(line) for line in lines if _layer_num(line) is not None]
    max_layer = max(layer_ns) if layer_ns else 0

    events: list[tuple[int, int, int]] = []
    for i, line in enumerate(lines):
        match = M73.match(_code(line))
        if not match:
            continue
        body = match.group("body")
        r_match = re.search(r"\bR(-?\d+(?:\.\d+)?)", body, re.I)
        p_match = re.search(r"\bP(-?\d+(?:\.\d+)?)", body, re.I)
        if r_match is None and p_match is None:
            continue
        r_min = float(r_match.group(1)) if r_match else None
        pct = float(p_match.group(1)) if p_match else None
        remaining = int(round(max(r_min, 0) * 60)) if r_min is not None else None
        if total is None and remaining is not None:
            total = remaining
        clock = _clock_from_m73(total, remaining, pct)
        if clock is None:
            continue
        events.append((i, clock[0], clock[1]))

    if total is None and events:
        total = events[0][1] + events[0][2]

    def times_at(line_idx: int, layer_n: int | None) -> tuple[int, int] | None:
        if total is None:
            return None
        if layer_n == 0:
            return 0, total
        prev = [event for event in events if event[0] <= line_idx]
        if prev:
            return prev[-1][1], prev[-1][2]
        if events:
            return 0, total
        if layer_n is not None and max_layer > 0:
            printed = int(round(total * layer_n / max_layer))
            printed = min(max(printed, 0), total)
            return printed, total - printed
        return 0, total

    out: list[str] = []
    changed = 0
    for i, line in enumerate(lines):
        if M73.match(_code(line)):
            changed += 1
            continue
        if _layer_marker(line, prefer_lc):
            already = (
                len(out) >= 2
                and out[-1].startswith(";REMAINING_TIME:")
                and out[-2].startswith(";PRINTING_TIME:")
            )
            pair = times_at(i, _layer_num(line))
            if not already and pair is not None:
                printed, remaining = pair
                out.append(f";PRINTING_TIME: {printed}")
                out.append(f";REMAINING_TIME: {remaining}")
                changed += 1
        out.append(line)

    if total is None:
        return out, changed

    firmware = next((i for i, line in enumerate(out[:120]) if line.startswith(";Firmware:")), None)
    if firmware is not None and not any(
        line.startswith(";Print Time:") for line in out[firmware : firmware + 12]
    ):
        block = _material_comments(total, mm, cost)
        out = out[: firmware + 1] + block + out[firmware + 1 :]
        changed += 1

    out, n_layer0 = _ensure_layer0_after_m1001(out, total)
    changed += n_layer0

    if not any(line.startswith(";Print Time:") for line in out[-40:]):
        out.extend(_material_comments(total, mm, cost))
        changed += 1

    return out, changed


def copy_slicer_height_after_layer(lines: list[str]) -> tuple[list[str], int]:
    """Place PrusaSlicer's reserved `;HEIGHT:` after `;LAYER:N` / `;Z:` (ideaMaker).

    Never put `HEIGHT` in custom G-code: PrusaSlicer warns that
    `HEIGHT:{layer_height}` in Before layer change G-code breaks visualization
    and print-time estimation. The slicer already emits `;HEIGHT:` on
    `;LAYER_CHANGE`; copy that value to the ideaMaker spot.
    """
    out: list[str] = []
    last_height: str | None = None
    changed = 0
    i = 0
    while i < len(lines):
        stripped = lines[i].strip()
        if HEIGHT_LINE.match(stripped):
            last_height = stripped
            out.append(lines[i])
            i += 1
            continue
        if _layer_num(lines[i]) is not None:
            out.append(lines[i])
            i += 1
            if i < len(lines) and Z_LINE.match(lines[i].strip()):
                out.append(lines[i])
                i += 1
            if last_height is not None and not (
                i < len(lines) and HEIGHT_LINE.match(lines[i].strip())
            ):
                out.append(last_height)
                changed += 1
            continue
        out.append(lines[i])
        i += 1
    return out, changed


def max_layer_z_from_gcode(lines: list[str]) -> float | None:
    """Highest post-M1001 `;Z:` layer tag (PrusaSlicer layer-change comment)."""
    zmax: float | None = None
    after_m1001 = False
    for line in lines:
        if _code(line).upper() == "M1001":
            after_m1001 = True
            continue
        if not after_m1001:
            continue
        match = Z_LINE.match(line.strip())
        if match:
            z = float(match.group(1))
            zmax = z if zmax is None else max(zmax, z)
    return zmax


def print_aabb_xy(lines: list[str]) -> tuple[float, float, float, float] | None:
    """Axis-aligned XY of G0/G1/G2/G3 after M1001 (print + wipe tower, not start purge)."""
    x: float | None = None
    y: float | None = None
    xmin = xmax = ymin = ymax = None
    relative = False
    in_print = False
    for line in lines:
        code = _code(line)
        if not code:
            continue
        upper = code.upper()
        if upper == "M1001":
            in_print = True
            continue
        if upper == "M1002":
            break
        if not in_print:
            continue
        if upper == "G90":
            relative = False
            continue
        if upper == "G91":
            relative = True
            continue
        if not MOVE_CMD.match(code):
            continue
        axes = {m.group(1).upper(): float(m.group(2)) for m in AXIS_XY.finditer(code)}
        if relative:
            if x is None or y is None:
                continue
            if "X" in axes:
                x += axes["X"]
            if "Y" in axes:
                y += axes["Y"]
        else:
            if "X" in axes:
                x = axes["X"]
            if "Y" in axes:
                y = axes["Y"]
        if x is None or y is None:
            continue
        xmin = x if xmin is None else min(xmin, x)
        xmax = x if xmax is None else max(xmax, x)
        ymin = y if ymin is None else min(ymin, y)
        ymax = y if ymax is None else max(ymax, y)
    if xmin is None:
        return None
    return xmin, ymin, xmax, ymax


def _format_bounding_box(
    xmin: float, ymin: float, xmax: float, ymax: float, zmax: float
) -> str:
    """ideaMaker header: xmin xmax ymin ymax zmin zmax."""
    return f";Bounding Box: {xmin:.3f} {xmax:.3f} {ymin:.3f} {ymax:.3f} 0.000 {zmax:.3f}"


def _ideamaker_bbox_ok(line: str) -> bool:
    match = BBOX_LINE.match(line.strip())
    if not match:
        return False
    xmin, xmax, ymin, ymax = (float(match.group(i)) for i in range(1, 5))
    return xmax >= xmin and ymax >= ymin


def inject_bounding_box(lines: list[str]) -> tuple[list[str], int]:
    """ideaMaker header AABB. `{max_layer_z}` is not valid in start G-code."""
    zmax = max_layer_z_from_gcode(lines)
    if zmax is None:
        return lines, 0
    firmware = next((i for i, line in enumerate(lines[:120]) if line.startswith(";Firmware:")), None)
    if firmware is None:
        return lines, 0
    xy = print_aabb_xy(lines)
    if xy is None:
        xmin, ymin, xmax, ymax = 0.0, 0.0, 305.0, 305.0
    else:
        xmin, ymin, xmax, ymax = xy
    box = _format_bounding_box(xmin, ymin, xmax, ymax, zmax)
    existing_i = next(
        (i for i, line in enumerate(lines[:80]) if line.startswith(";Bounding Box:")),
        None,
    )
    if existing_i is not None:
        if _ideamaker_bbox_ok(lines[existing_i]):
            return lines, 0
        out = list(lines)
        out[existing_i] = box
        return out, 1
    return lines[: firmware + 1] + [box] + lines[firmware + 1 :], 1


def rewrite(path: Path) -> str:
    """Move M99123 to line 1, convert M204, insert next-tool preheat.

    Returns 'moved', 'already', or 'missing' (M99123 status).
    """
    raw = path.read_bytes()
    newline = b"\r\n" if b"\r\n" in raw else b"\n"
    text = raw.decode("utf-8-sig", errors="replace")
    lines = text.splitlines()
    lines, n_m204 = convert_m204_lines(lines)
    lines, n_preheat = insert_next_tool_preheat(lines)
    lines, n_times = emit_raisetouch_times(lines)
    lines, n_height = copy_slicer_height_after_layer(lines)
    lines, n_bbox = inject_bounding_box(lines)
    idx = next((i for i, line in enumerate(lines) if line.startswith("M99123")), None)
    moved = False
    if idx is not None and idx != 0:
        header = lines.pop(idx)
        lines.insert(0, header)
        moved = True
    if moved or n_m204 or n_preheat or n_times or n_height or n_bbox:
        path.write_bytes((newline.decode("ascii").join(lines) + newline.decode("ascii")).encode("utf-8"))
    if idx is None:
        return "missing"
    return "moved" if moved else "already"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "gcode",
        nargs="?",
        type=Path,
        help="G-code path (PrusaSlicer post-process passes this as the last arg)",
    )
    args, extra = parser.parse_known_args(argv)
    path = args.gcode
    if extra:
        # Post-process: slicer may pass flags then the temp file as the last token.
        path = Path(extra[-1])
    if path is None:
        parser.error("gcode path required")
    if not path.is_file():
        print(f"not found: {path}", file=sys.stderr)
        return 1
    raw_before = path.read_text(encoding="utf-8", errors="replace")
    m204_before = sum(1 for line in raw_before.splitlines() if M204_S.match(line.split(";", 1)[0].strip()))
    result = rewrite(path)
    extra_msg = f", converted {m204_before} M204 to SET_VELOCITY_LIMIT" if m204_before else ""
    after = path.read_text(encoding="utf-8", errors="replace")
    if "next-tool preheat" in after:
        extra_msg += ", inserted next-tool M104 preheat"
    if ";REMAINING_TIME:" in after:
        extra_msg += ", wrote RaiseTouch PRINTING_TIME/REMAINING_TIME"
    if result == "missing":
        print(f"FAIL {path}: no M99123 line to move{extra_msg}", file=sys.stderr)
        return 1
    if result == "already":
        print(f"OK {path}: M99123 already on line 1{extra_msg}")
    else:
        print(f"OK {path}: moved M99123 to line 1{extra_msg}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
